language: python
python: 3.5
sudo: false
services: redis-server
env:
    - TOX_ENV=py35
    - TOX_ENV=flake8
    - TOX_ENV=docs
install:
    - if [[ $ACTION != loadtest ]]; then pip install tox; fi
script:
    - if [[ $ACTION != loadtest ]]; then tox -e $TOX_ENV; fi
